permissions:
  contents: read

on:
  workflow_call:
    inputs:
      deploy-envs:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      prod:
        required: false
        type: boolean
        default: false
    secrets:
      SLACK_DEPLOYMENTS_CHANNEL_ID:
        required: true
      REPO_DISPATCH_PAT_TOKEN:
        required: true
      MINDSDB_DB_URI:
        required: true

jobs:
  migrate:
    if: github.actor != 'mindsdbadmin'
    runs-on: ${{ matrix.deploy-env == 'prod' && 'mdb-prod' || 'mdb-dev' }}
    strategy:
      fail-fast: false
      matrix:
        deploy-env: ${{ fromJson(inputs.deploy-envs) }}
    environment:
      name: ${{ matrix.deploy-env }}
      url: ${{ vars.MDB_ENV_URL }}
    # We only want to run one deploy job for an env at a time
    # Don't cancel in progress jobs because it may be for a different PR
    concurrency:
      group: deploy-${{ matrix.deploy-env }}
      cancel-in-progress: false
    env:
      MINDSDB_DB_CON: ${{ secrets.MINDS_DB_URI }}
      UV_LINK_MODE: "symlink"
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          # Place cache in the tool dir because we mount this in our runnners
          cache-local-path: "/home/runner/_work/_tool/uv-local-cache"
          prune-cache: false
          python-version: ${{ vars.CI_PYTHON_VERSION || '3.10' }}
      - name: Install dependencies
        run: |
          uv pip install --prerelease=allow -r requirements/requirements.txt
      - name: Migrate DB
        run: |
          cd mindsdb/migrations
          env PYTHONPATH=../../ alembic upgrade head


  # Trigger private repo to deploy
  trigger_deploy:
    if: github.actor != 'mindsdbadmin'
    needs: migrate
    runs-on: mdb-dev
    strategy:
      fail-fast: false
      matrix:
        deploy-env: ${{ fromJson(inputs.deploy-envs) }}
    environment:
      name: ${{ matrix.deploy-env }}
      url: ${{ vars.MDB_ENV_URL }}
    # We only want to run one deploy job for an env at a time
    # Don't cancel in progress jobs because it may be for a different PR
    concurrency:
      group: deploy-${{ matrix.deploy-env }}
      cancel-in-progress: false
    steps:
    - name: Pull MindsDB Github Actions
      uses: actions/checkout@v4
      with:
        repository: mindsdb/github-actions
        path: github-actions
    - uses: FranzDiebold/github-env-vars-action@v2
    - name: Notify of deployment starting
      id: slack
      uses: ./github-actions/slack-deploy-msg
      with:
        channel-id: ${{ secrets.SLACK_DEPLOYMENTS_CHANNEL_ID }}
        status: "started"
        color: "#0099CC"
        env-name: ${{ matrix.deploy-env }}
        env-url: ${{ vars.MDB_ENV_URL }}
        slack-token: ${{ secrets.GH_ACTIONS_SLACK_BOT_TOKEN }}
    - uses: ./github-actions/dispatch-and-wait
      with:
        owner: mindsdb
        repo: INTERNAL-mindsdb-build-deploy-to-kubernetes
        token: ${{ secrets.REPO_DISPATCH_PAT_TOKEN }}
        workflow: ${{ inputs.prod && 'deploy-prod.yml' || 'deploy-dev.yml' }}
        workflow_inputs: '{"image-tag-prefix": "${{ inputs.image-tag }}", "deploy-env": "${{ matrix.deploy-env }}"}'
    - name: Notify of deployment finish
      uses: ./github-actions/slack-deploy-msg
      if: always()
      with:
        channel-id: ${{ secrets.SLACK_DEPLOYMENTS_CHANNEL_ID }}
        status: "${{ job.status == 'success' && 'finished' || 'failed' }}"
        color: "${{ job.status == 'success' && '#00C851' || '#FF4444' }}"
        env-name: ${{ matrix.deploy-env }}
        env-url: ${{ vars.MDB_ENV_URL }}
        slack-token: ${{ secrets.GH_ACTIONS_SLACK_BOT_TOKEN }}
        update-message-id: ${{ steps.slack.outputs.ts }}