


<div
  style="height: auto; display: flex; flex-direction: column; align-items: flex-end; justify-content: center; border-radius: 30px; width: 360px; position: fixed; right: 1.5rem; bottom: 4rem;">
  <div id="ig-chat-container" style="display:flex;justify-content:center;align-items:center;flex-direction:column;width: 100%;background-color:#ffffff;border-radius:0.375rem;font-family:sans-serif;
      padding-bottom: 1rem; opacity: 1; transform: translateY(0%); visibility: visible; border: 1px solid #E3E5F5;
      transition: transform 0.4s cubic-bezier(0.4, 0, 0.2, 1), opacity 0.4s cubic-bezier(0.4, 0, 0.2, 1);
      visibility: hidden;" onclick="const el = document.getElementById('ig-chat-container');
                    if (el) {
                      el.style.visibility = 'hidden';
                      el.style.transform = 'translateY(100%)';
                      el.style.opacity = '0';
                    }
                    const button = document.getElementById('ig-chat-button');
                    if (button) {
                      button.style.visibility = 'visible';
                      button.style.transform = 'translateY(0%)';
                      button.style.opacity = '1';
                    }">
    <div style="display: flex; justify-content: flex-start; align-items: center; flex-direction: row; width: -webkit-fill-available; height: auto; padding: 1rem; gap: 1.25rem;
      position: relative;">
      <div
        style="display: flex; justify-content: center; align-items: center; width: 3rem; height: 3rem; background-color: #f8fafc; border-radius: 9999px; position: relative; padding: 0.125rem;">
        <img
          src="https://www.jotform.com/uploads/bshvb0/agent_files/avatar_images/IMG_0902-691ae195410c76.78443502.png"
          alt="agent-avatar"
          style="width: 2.75rem; height: 2.75rem; background-color: #f8fafc; border-radius: 9999px;">
        <div style="width: 1rem; height: 1rem; display: flex; align-items: center; justify-content: center; background-color: #ffffff; border-radius: 9999px;
          position: absolute; bottom: 0px; right: -0.125rem;">
          <div
            style="width: 0.75rem; height: 0.75rem; background-color: #22c55e; border-radius: 9999px;">
          </div>
        </div>
      </div>
      <div
        style="display: flex; justify-content: center; align-items: flex-start; flex-direction: column; flex-grow: 1;">
        <p style="font-weight: 700; color: #334155; margin: 0.25rem;">goodshytgroup</p>
        <p style="font-weight: 500; color: #334155; margin: 0.25rem;">Online</p>
      </div>
      <button type="button"
        style="position: absolute; top: 0px; right: 0px; display: inline-flex; flex-shrink: 0; justify-content: center; align-items: center;
        font-weight: 500; transition-duration: 300ms; outline-width: 2px; outline-color: transparent; outline-offset: 0px; height: 2rem; padding-left: 0.5rem;
        padding-right: 0.5rem; border-width: 0px; cursor: pointer; background-color: transparent; color: #334155;">
        <span
          style="padding-left: 0.25rem; padding-right: 0.25rem; font-size: 0.875rem; line-height: 1.25rem;">
          x</span>
      </button>
    </div>
    <div style="width: 100%; height: 1px; padding-bottom: 0.5rem; border-top: 1px solid #E3E5F5">
    </div>
    <div
      style="display: flex; justify-content: flex-start; align-items: flex-start; flex-direction: row; width: -webkit-fill-available; height: auto; padding: 1rem;gap: 1.25rem;">
      <img
        src="https://www.jotform.com/uploads/bshvb0/agent_files/avatar_images/IMG_0902-691ae195410c76.78443502.png"
        alt="agent-avatar"
        style="width: 2.5rem; height: 2.5rem; background-color: #f8fafc; border-radius: 9999px;">
      <div style="display: flex; justify-content: flex-start; align-items: flex-start; flex-direction: column; flex-grow: 1; border-radius: 0.375rem; background-color: #fafafa;
          padding-left: 1rem;">
        <p style="color: #334155; margin: 0.25rem;">Hi there! ðŸŒŸ</p>
        <p style="color: #334155; margin: 0.25rem;">How can I help you?</p>
      </div>
    </div>
    <button type="button" style="border-radius: 9999px; display: inline-flex; flex-shrink: 0; justify-content: center; align-items: center; font-weight: 500; transition-duration: 300ms;
      outline-width: 2px; outline-color: transparent; outline-offset: 0px; height: 3rem; padding: 0 0.75rem; border-width: 0px; cursor: pointer; color: #ffffff;
      background-color: #3b82f6;" onclick="window.location.href = 'https://ig.me/m/goodshytgroup'">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
        viewBox="0 0 24 24">
        <path
          d="M12 1c-2.987 0-3.362.019-4.535.067-1.17.054-1.968.237-2.668.51a5.403 5.403 0 0 0-1.95 1.27A5.384 5.384 0 0 0 1.58 4.794c-.272.7-.46 1.501-.513 2.672C1.014 8.64 1 9.014 1 12.002c0 2.987.014
    3.362.067 4.535.054 1.171.24 1.97.513 2.669a5.383 5.383 0 0 0 1.266 1.948 5.417 5.417 0 0 0 1.951 1.27c.7.272 1.498.459 2.668.512C8.638 22.99 9.013 23 12 23s3.362-.017
    4.535-.064c1.17-.053 1.972-.24 2.671-.512a5.393 5.393 0 0 0
    1.948-1.27 5.384 5.384 0 0 0 1.267-1.948c.271-.7.458-1.498.512-2.669.053-1.173.067-1.547.067-4.535 0-2.988-.014-3.362-.067-4.536-.054-1.17-.24-1.972-.512-2.672a5.384 5.384
    0 0 0-1.267-1.947 5.392 5.392 0 0 0-1.948-1.27c-.7-.273-1.5-.456-2.671-.51C15.362 1.014 14.987 1 12 1Zm0 1.981c2.937 0 3.284.018 4.444.064 1.072.048 1.657.23 2.045.38.513.2.878.438
    1.263.823a3.4 3.4 0
    0 1 .822 1.264c.15.387.332.973.38 2.045.054 1.16.065 1.507.065 4.445 0 2.937-.012 3.284-.064 4.444-.05 1.073-.23 1.654-.38 2.042-.2.514-.438.882-.823
    1.267-.385.385-.75.623-1.263.822-.388.15-.973.329-2.045.378-1.16.053-1.507.064-4.444.064-2.937
    0-3.284-.018-4.444-.064-1.072-.049-1.654-.227-2.041-.378a3.415 3.415 0 0 1-1.267-.822 3.416 3.416 0 0
    1-.822-1.267c-.15-.387-.329-.97-.378-2.042-.052-1.16-.064-1.507-.064-4.444 0-2.938.013-3.285.064-4.445.05-1.072.227-1.658.378-2.045.2-.514.437-.879.822-1.264a3.415 3.415 0 0 1
    1.267-.822c.387-.15.969-.332 2.041-.38C8.716 2.991 9.063 2.98 12 2.98Zm5.872 1.827a1.321 1.321 0 1 0 .002 2.642 1.321 1.321 0 0 0-.002-2.642ZM12 6.35A5.649 5.649 0 0 0 6.353 12 5.649 5.649
    0 1 0 12 6.352Zm0 1.985a3.665 3.665 0 0 1 3.665 3.666 3.665 3.665 0 1 1-7.33 0A3.665 3.665 0 0 1 12 8.336Z" />
      </svg>
      <span style="padding: 0 0.75rem; font-size: 1.125rem; line-height: 1.75rem;">Message on
        Instagram</span>
    </button>
  </div>
  <button id="ig-chat-button" type="button"
    style="border-radius: 9999px; display: inline-flex; flex-shrink: 0; justify-content: center; align-items: center; font-weight: 500;
    transition-duration: 300ms; outline-width: 2px; outline-color: transparent; outline-offset: 0px; height: 3rem; padding-left: 0.75rem; padding-right: 0.75rem; cursor: pointer;
    background-color: #ffffff; color: #4b5563; transform: translateY(100%); border: 1px solid #E3E5F5;" onclick="const el = document.getElementById('ig-chat-container');
                if (el) {
                  el.style.visibility = 'visible';
                  el.style.transform = 'translateY(0%)';
                  el.style.opacity = '1';
                }
                const button = document.getElementById('ig-chat-button');
                if (button) {
                  button.style.visibility = 'hidden';
                  button.style.transform = 'translateY(100%)';
                  button.style.opacity = '0';
                }">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
      viewBox="0 0 24 24">
      <path
        d="M12 1c-2.987 0-3.362.019-4.535.067-1.17.054-1.968.237-2.668.51a5.403 5.403 0 0 0-1.95 1.27A5.384 5.384 0 0 0 1.58 4.794c-.272.7-.46 1.501-.513 2.672C1.014 8.64 1 9.014 1 12.002c0 2.987.014
    3.362.067 4.535.054 1.171.24 1.97.513 2.669a5.383 5.383 0 0 0 1.266 1.948 5.417 5.417 0 0 0 1.951 1.27c.7.272 1.498.459 2.668.512C8.638 22.99 9.013 23 12 23s3.362-.017
    4.535-.064c1.17-.053 1.972-.24 2.671-.512a5.393 5.393 0 0 0
    1.948-1.27 5.384 5.384 0 0 0 1.267-1.948c.271-.7.458-1.498.512-2.669.053-1.173.067-1.547.067-4.535 0-2.988-.014-3.362-.067-4.536-.054-1.17-.24-1.972-.512-2.672a5.384 5.384
    0 0 0-1.267-1.947 5.392 5.392 0 0 0-1.948-1.27c-.7-.273-1.5-.456-2.671-.51C15.362 1.014 14.987 1 12 1Zm0 1.981c2.937 0 3.284.018 4.444.064 1.072.048 1.657.23 2.045.38.513.2.878.438
    1.263.823a3.4 3.4 0
    0 1 .822 1.264c.15.387.332.973.38 2.045.054 1.16.065 1.507.065 4.445 0 2.937-.012 3.284-.064 4.444-.05 1.073-.23 1.654-.38 2.042-.2.514-.438.882-.823
    1.267-.385.385-.75.623-1.263.822-.388.15-.973.329-2.045.378-1.16.053-1.507.064-4.444.064-2.937
    0-3.284-.018-4.444-.064-1.072-.049-1.654-.227-2.041-.378a3.415 3.415 0 0 1-1.267-.822 3.416 3.416 0 0
    1-.822-1.267c-.15-.387-.329-.97-.378-2.042-.052-1.16-.064-1.507-.064-4.444 0-2.938.013-3.285.064-4.445.05-1.072.227-1.658.378-2.045.2-.514.437-.879.822-1.264a3.415 3.415 0 0 1
    1.267-.822c.387-.15.969-.332 2.041-.38C8.716 2.991 9.063 2.98 12 2.98Zm5.872 1.827a1.321 1.321 0 1 0 .002 2.642 1.321 1.321 0 0 0-.002-2.642ZM12 6.35A5.649 5.649 0 0 0 6.353 12 5.649 5.649
    0 1 0 12 6.352Zm0 1.985a3.665 3.665 0 0 1 3.665 3.666 3.665 3.665 0 1 1-7.33 0A3.665 3.665 0 0 1 12 8.336Z" />
    </svg>
  </button>
</div>
https://ig.me/m/goodshytgroup
https://www.jotform.com/agent/019a90feb6697ac0ab905ef2541077d3e756
